version: '4'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    command: ["postgres", "-c", "log_statement=all"]